server:
  #端口号
  port: 80
  connection-timeout: 2000
    


 

    

mybatis:
  type-aliases-package: com.mushroom.pojo,com.mushroom.merchant.vo
  mapper-locations: classpath:mapper/*.xml,mappers/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.139.220:3306/mokopay?serverTimezone=GMT
    username: root
    password: 123
  resources:
    static-locations: classpath:/templates/
  redis:
    database: 0
    timeout: 5000s
    host:  111.230.139.220
    password: 123456
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
# 连接池最大连接数（使用负值表示没有限制）
  pool:
    max-active: 50
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
# 连接池中的最大空闲连接
    max-idle: 8
# 连接池中的最小空闲连接
    min-idle: 0
  data:
    solr:
      host: http://111.230.139.220:8983/solr/mushroom
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8 

#thymeleaf start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
    


#thymeleaf end


#pagehelper分页插件配置
pagehelper:
  reasonable: true
  
logging:
  config: 
  level:
    root: error
    
    
